CREATE TABLE FIRSTNAME
(
	FIRSTNAME VARCHAR(50)
)

INSERT INTO FIRSTNAME
SELECT DISTINCT FirstName
FROM AdventureWorks2017.Person.Person

CREATE TABLE MIDDLENAME
(
	MIDDLENAME VARCHAR(255)
)

INSERT INTO MIDDLENAME
SELECT DISTINCT middleName
FROM RandomData.DBO.person

CREATE TABLE LASTNAME
(
	LASTNAME VARCHAR(50)
)

INSERT INTO LASTNAME
SELECT DISTINCT LastName
FROM AdventureWorks2017.Person.Person

CREATE TABLE ADDRESS
(
	ADDRESS VARCHAR(50)
)

INSERT INTO ADDRESS
SELECT DISTINCT AddressLine1
FROM AdventureWorks2017.Person.Address

CREATE TABLE EMAILADDRESS
(
 	EMAILADDRESS VARCHAR(50)
)

INSERT INTO EMAILADDRESS
SELECT TOP(2000) EmailAddress
FROM AdventureWorks2017.Person.EmailAddress