--DROP TABLE #TEMP

CREATE TABLE #TEMP
(
VALUE VARCHAR(MAX)
)

INSERT INTO #TEMP

SELECT OLFDataVarcharValues.result_value

FROM OLFDataVarcharValues

WHERE result_value <> ''


SELECT TOP (10000)
*
FROM #TEMP
WHERE VALUE LIKE '%PATIENT%'

UPDATE #TEMP
SET

VALUE = 
CASE
	WHEN CHARINDEX('CASE NUMBER',VALUE) <> 0 AND CHARINDEX('PATIENT',VALUE) <> 0
	THEN CONCAT(LEFT(VALUE,CHARINDEX('PATIENT',VALUE) +7),RIGHT(VALUE, LEN(VALUE) - CHARINDEX('CASE NUMBER',VALUE) +1))

	ELSE
		VALUE
END

UPDATE #TEMP
SET

VALUE = REPLACE(VALUE,'1280 116th Ave NE, Bellevue, WA', '850 EAST SPOKANE FALLS BLVD., SUITE 124, SPOKANE, WA 99202.')


UPDATE #TEMP
SET

VALUE = REPLACE(VALUE,'13103 E. Mansfield Ave., Spokane Valley, WA 99216', '850 EAST SPOKANE FALLS BLVD., SUITE 124, SPOKANE, WA 99202.')


UPDATE #TEMP
SET

VALUE = 
CASE
	WHEN
		CHARINDEX('INCYTE DIAGNOSTICS', VALUE) <> 0
		THEN REPLACE(VALUE, 'INCYTE DIAGNOSTICS', 'GESTALT DIAGNOSTIC LABORATORIES')

	WHEN
		CHARINDEX('INCYTE', VALUE) <> 0
		THEN REPLACE(VALUE, 'INCYTE', 'GESTALT DIAGNOSTIC LABORATORIES')

	WHEN
		CHARINDEX('SOUTHLAKE CLINIC', VALUE) <> 0
		THEN REPLACE(VALUE, 'SOUTHLAKE CLINIC', 'GESTALT DIAGNOSTIC LABORATORIES')

	WHEN
		CHARINDEX('PUYALLUP SURGICAL', VALUE) <> 0
		THEN REPLACE(VALUE, 'PUYALLUP SURGICAL', 'GESTALT DIAGNOSTIC LABORATORIES')  
		
	WHEN
		CHARINDEX('UNIPATH', VALUE) <> 0
		THEN REPLACE(VALUE, 'UNIPATH', 'GESTALT DIAGNOSTIC LABORATORIES')  

	WHEN
		CHARINDEX('PSHMC', VALUE) <> 0
		THEN CONCAT(VALUE, 'PSHMC', 'GESTALT DIAGNOSTIC LABORATORIES')  	

	WHEN
		CHARINDEX('PULLMAN REGIONAL', VALUE) <> 0
		THEN REPLACE(VALUE, 'PULLMAN REGIONAL', 'GESTALT DIAGNOSTIC LABORATORIES') 

	ELSE
		VALUE
END

SELECT TOP (10000)
*
FROM #TEMP
WHERE VALUE LIKE '%PATIENT%'
AND VALUE NOT LIKE '%GESTALT%'
AND VALUE LIKE '%PERFORMING LABORATORY%'

DROP TABLE #TEMP