--DROP TABLE #TEMPTABLE

CREATE TABLE #TEMPTABLE
(
	FNAME VARCHAR(50),
	MNAME VARCHAR(50),
	LNAME VARCHAR(50),
	PKEY VARCHAR(100),
	CATEGORY VARCHAR(50),
	VALUE NVARCHAR(MAX)
)

INSERT INTO #TEMPTABLE


SELECT --TOP(100000)
Contact.givenName,
Contact.middleName,
Contact.familyName,
ResultSection.resultSectionKey,
ResultSection.sectionCategory,
ResultSection.sectionValue



FROM 

Patient LEFT JOIN mapPatientContact ON Patient.patientKey = mapPatientContact.patientKey
LEFT JOIN Contact ON mapPatientContact.contactKey = Contact.contactKey
LEFT JOIN mapContactAddress ON Contact.contactKey = mapContactAddress.contactKey
LEFT JOIN Address ON mapContactAddress.addressKey = Address.addressKey
LEFT JOIN mapContactPhoneNumber ON Contact.contactKey = mapContactPhoneNumber.contactKey
LEFT JOIN PhoneNumber ON mapContactPhoneNumber.phoneNumberKey = PhoneNumber.phoneNumberKey
LEFT JOIN mapContactEmailAddress ON Contact.contactKey = mapContactEmailAddress.contactKey
LEFT JOIN EmailAddress ON mapContactEmailAddress.emailAddressKey = EmailAddress.emailAddressKey
LEFT JOIN FillerOrder ON Patient.patientKey = FillerOrder.patientKey
LEFT JOIN RequestedProcedure ON FillerOrder.fillerOrderKey = RequestedProcedure.fillerOrderKey
LEFT JOIN mapResultRequestedProcedure ON RequestedProcedure.requestedProcedureKey = mapResultRequestedProcedure.requestedProcedureKey
LEFT JOIN ResultSection ON mapResultRequestedProcedure.resultKey = ResultSection.resultKey

WHERE ResultSection.sectionValue <> ''
--AND ResultSection.sectionCategory = 'HEADER'
--AND ResultSection.sectionCategory = 'COMMENT'
--AND ResultSection.sectionCategory = 'SIGNATURE'
--AND ResultSection.sectionCategory = 'PERFORMING LABORATORY'
SELECT *
FROM #TEMPTABLE
ORDER BY LNAME

/*
UPDATE #TEMPTABLE
SET

VALUE = REPLACE(VALUE,FNAME, '')


UPDATE #TEMPTABLE
SET

VALUE = 
CASE 
	WHEN 
		MNAME IS NOT NULL  AND LEN(MNAME) > 1
		THEN REPLACE(VALUE,MNAME, '') 
		
	ELSE 
		VALUE 

END


UPDATE #TEMPTABLE
SET

VALUE = REPLACE(VALUE,LNAME, '')

*/

--REMOVE NAME FROM HEADER
UPDATE #TEMPTABLE
SET

VALUE =
CASE
	WHEN
		CHARINDEX('CASE NUMBER',VALUE) <> 0
		THEN RIGHT(VALUE, LEN(VALUE) - CHARINDEX('CASE NUMBER',VALUE) +2)

	WHEN 
		CHARINDEX('NUMBER',VALUE) <> 0
		THEN RIGHT(VALUE, LEN(VALUE) - CHARINDEX('NUMBER',VALUE) +2)

	ELSE
		VALUE 

END

WHERE CATEGORY = 'HEADER'


--CREATE CUSTOM SIGNATURE
UPDATE #TEMPTABLE
SET

VALUE = CONCAT('FINAL BY GESTALT DIAGNOSTIC LABORATORIES. ELECTRONICALLY SIGNED  ', CONVERT(VARCHAR,DATEADD(DAY, (ABS(CHECKSUM(NEWID())) % (DATEDIFF(DAY, '1900/01/01',GETDATE()))), 0),9))
WHERE CATEGORY = 'SIGNATURE'


-- REPLACE PERFORMING LABORATORY
UPDATE #TEMPTABLE
SET

VALUE = 
CASE
	WHEN
		CHARINDEX('INCYTE', VALUE) <> 0
		THEN CONCAT(SUBSTRING(VALUE, 0, CHARINDEX('INCYTE', VALUE)), 'GESTALT DIAGNOSTIC LABORATORIES, 850 EAST SPOKANE FALLS BLVD., SUITE 124, SPOKANE, WA 99202.')

	WHEN
		CHARINDEX('SOUTHLAKE CLINIC', VALUE) <> 0
		THEN CONCAT(SUBSTRING(VALUE, 0, CHARINDEX('SOUTHLAKE CLINIC', VALUE)), 'GESTALT DIAGNOSTIC LABORATORIES, 850 EAST SPOKANE FALLS BLVD., SUITE 124, SPOKANE, WA 99202.')

	WHEN
		CHARINDEX('PUYALLUP SURGICAL', VALUE) <> 0
		THEN CONCAT(SUBSTRING(VALUE, 0, CHARINDEX('PUYALLUP SURGICAL', VALUE)), 'GESTALT DIAGNOSTIC LABORATORIES, 850 EAST SPOKANE FALLS BLVD., SUITE 124, SPOKANE, WA 99202.')  
		
	WHEN
		CHARINDEX('UNIPATH', VALUE) <> 0
		THEN CONCAT(SUBSTRING(VALUE, 0, CHARINDEX('UNIPATH', VALUE)), 'GESTALT DIAGNOSTIC LABORATORIES, 850 EAST SPOKANE FALLS BLVD., SUITE 124, SPOKANE, WA 99202.')  

	WHEN
		CHARINDEX('PSHMC', VALUE) <> 0
		THEN CONCAT(SUBSTRING(VALUE, 0, CHARINDEX('PSHMC', VALUE)), 'GESTALT DIAGNOSTIC LABORATORIES, 850 EAST SPOKANE FALLS BLVD., SUITE 124, SPOKANE, WA 99202.')  	

	WHEN
		CHARINDEX('PULLMAN REGIONAL', VALUE) <> 0
		THEN CONCAT(SUBSTRING(VALUE, 0, CHARINDEX('PULLMAN REGIONAL', VALUE)), 'GESTALT DIAGNOSTIC LABORATORIES, 850 EAST SPOKANE FALLS BLVD., SUITE 124, SPOKANE, WA 99202.')  

	WHEN
		CHARINDEX('PERFORMED AT', VALUE) <> 0
		THEN CONCAT(SUBSTRING(VALUE, 0, CHARINDEX('PERFORMED AT', VALUE)), 'GESTALT DIAGNOSTIC LABORATORIES, 850 EAST SPOKANE FALLS BLVD., SUITE 124, SPOKANE, WA 99202.') 
	
	ELSE 
		'PROFESSIONAL INTERPREATION WAS PERFORMED BY GESTALT DIAGNOSTIC LABORATORIES, 850 EAST SPOKANE FALLS BLVD., SUITE 124, SPOKANE, WA 99202.'		
END
	
WHERE CATEGORY = 'PERFORMING LABORATORY' 
OR CATEGORY = 'PERFORMING LABORATORY.'


UPDATE #TEMPTABLE
SET

VALUE = REPLACE(VALUE,'Incyte Diagnostics', 'GESTALT DIAGNOSTIC LABORATORIES')


UPDATE #TEMPTABLE
SET

VALUE = REPLACE(VALUE,'Incyte', 'GESTALT')

UPDATE #TEMPTABLE
SET

VALUE = REPLACE(VALUE,' 1280 116th Ave NE, Bellevue, WA', '850 EAST SPOKANE FALLS BLVD., SUITE 124, SPOKANE, WA 99202.')





/*
UPDATE #TEMPTABLE
SET

--VALUE = RIGHT(VALUE, LEN(VALUE) - CHARINDEX('M.D',VALUE) +2)
VALUE = 
CASE
	WHEN
		PATINDEX('%M.D%',VALUE) = 0
		THEN ''

	ELSE
		LEFT(VALUE, PATINDEX('%M.D%',VALUE) +5)

END

UPDATE #TEMPTABLE
SET

VALUE = SUBSTRING(VALUE,LEN(VALUE) -25, 25)


UPDATE #TEMPTABLE
SET

VALUE = LTRIM( RIGHT(VALUE, LEN(VALUE) - CHARINDEX(' ', VALUE)+1))

*/





/*
UPDATE #TEMPTABLE
SET

VALUE = 
CASE 
	WHEN 
		VALUE LIKE '%FINAL BY%' 
		THEN '' 

	WHEN 
		VALUE LIKE '%FINA BY%' 
		THEN '' 

	WHEN 
		VALUE LIKE '%INAL BY%' 
		THEN '' 

	WHEN 
		VALUE LIKE '%FINL BY%' 
		THEN '' 

	WHEN 
		VALUE LIKE '%%BY INCYTE DIAGNO%' 
		THEN '' 

	WHEN 
		VALUE LIKE '%DIAGNOSIS BY%' 
		THEN '' 

	WHEN 
		VALUE LIKE '%PERFORMED BY%' 
		THEN '' 
		
	WHEN 
		VALUE LIKE '%EVALUATION BY%' 
		THEN '' 
		
	WHEN 
		VALUE LIKE '%MOLECULAR TESTING%' 
		THEN '' 
		
	WHEN 
		VALUE LIKE '%TECHNICAL PEPAATION%' 
		THEN '' 
	
	WHEN 
		VALUE LIKE '%TECHNICAL PREPARATION%' 
		THEN '' 
	
	WHEN 
		VALUE LIKE '%PROFESSIONAL INTERPRETATION%' 
		THEN ''  
	
	WHEN 
		VALUE LIKE '%DICTATION BY%' 
		THEN '' 
		
	ELSE 
		VALUE 
		
END

*/





SELECT * --DISTINCT VALUE
FROM #TEMPTABLE
WHERE VALUE <>''
--AND CATEGORY = 'SIGNATURE'
--AND CATEGORY = 'HEADER'
--AND CATEGORY = 'PERFORMING LABORATORY'
--AND VALUE LIKE '%(MEDICAL DIRECTOR%'
--AND VALUE LIKE '%INCYTE%'
--AND VALUE NOT LIKE '%CASE NUMBER%'
--AND VALUE NOT LIKE 'ASE NUMBER%'
--AND VALUE NOT LIKE ' CASE%'
--AND VALUE NOT LIKE 'NUMBER%'
--AND VALUE NOT LIKE 'UMBER%'
--AND VALUE NOT LIKE '%GESTALT%'
--ORDER BY LNAME

DROP TABLE #TEMPTABLE